name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
      - name: Get NPM package version
        id: npm_package
        run: echo "::set-output name=version::$(npm run version --silent)"
      - name: Docker build
        run: docker build -t k0rdan/setup-terraform-cloud:${{ steps.npm_package.outputs.version }}-$(date +"%Y%m%d")-$GITHUB_RUN_NUMBER-$GITHUB_SHA .
      - name: Docker upload
        if: ${{ !env.ACT }}
        run: docker upload k0rdan/setup-terraform-cloud:${{ steps.npm_package.outputs.version }}-$(date +"%Y%m%d")-$GITHUB_RUN_NUMBER-$GITHUB_SHA
